# Generated by Django 2.2.22 on 2021-05-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Add your post title here.', max_length=63)),
                ('slug', models.SlugField(help_text='A label for URL config.', max_length=63, unique_for_month='pub_date')),
                ('text', models.TextField(help_text='Add your post body here.')),
                ('pub_date', models.DateField(auto_now_add=True, help_text='It will not be seen in admin.', verbose_name='date published')),
                ('startups', models.ManyToManyField(related_name='blog_post', to='organizer.Startup')),
                ('tags', models.ManyToManyField(related_name='blog_post', to='organizer.Tag')),
            ],
        ),
    ]
