# Generated by Django 2.2.22 on 2021-05-19 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Add your tag name here.', max_length=31, unique=True)),
                ('slug', models.SlugField(help_text='A label for URL config.', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Add your startup name here.', max_length=31)),
                ('slug', models.SlugField(help_text='A label for URL config.', max_length=31, unique=True)),
                ('description', models.TextField(help_text='Add the body of startup here.')),
                ('founded_date', models.DateField(verbose_name='date founded')),
                ('contact', models.EmailField(help_text='Add your email here.', max_length=225)),
                ('website', models.URLField(help_text='Add your website domain/url here.')),
                ('tags', models.ManyToManyField(to='organizer.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='NewsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Add the title here.', max_length=63)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('link', models.URLField(help_text='Add/paste the link here.', max_length=225)),
                ('startup', models.ForeignKey(help_text='Click the v sign.', on_delete=django.db.models.deletion.CASCADE, to='organizer.Startup')),
            ],
        ),
    ]
