# Generated by Django 2.1 on 2021-05-19 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslink',
            options={'get_latest_by': 'pub_date', 'ordering': ['-pub_date'], 'verbose_name': 'article link', 'verbose_name_plural': 'article links'},
        ),
        migrations.AlterField(
            model_name='newslink',
            name='link',
            field=models.URLField(help_text='Add/paste the link here.', max_length=225),
        ),
        migrations.AlterField(
            model_name='newslink',
            name='startup',
            field=models.ForeignKey(help_text='Click the v sign.', on_delete=django.db.models.deletion.CASCADE, to='organizer.Startup'),
        ),
        migrations.AlterField(
            model_name='newslink',
            name='title',
            field=models.CharField(help_text='Add the title here.', max_length=63),
        ),
        migrations.AlterField(
            model_name='startup',
            name='contact',
            field=models.EmailField(help_text='Add your email here.', max_length=225),
        ),
        migrations.AlterField(
            model_name='startup',
            name='description',
            field=models.TextField(help_text='Add the body of startup here.'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='name',
            field=models.CharField(db_index=True, help_text='Add your startup name here.', max_length=31),
        ),
        migrations.AlterField(
            model_name='startup',
            name='website',
            field=models.URLField(help_text='Add your website domain/url here.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Add your tag name here.', max_length=31, unique=True),
        ),
    ]
